DROP TABLE IF EXISTS "knex_migrations";
CREATE TABLE "knex_migrations" ("id" integer not null primary key autoincrement, "name" varchar(255), "batch" integer, "migration_time" datetime);
INSERT INTO "knex_migrations" VALUES(1,'20160915162159_users.js',1,1473915742674);
INSERT INTO "knex_migrations" VALUES(2,'20160915162208_movies.js',1,1473915742685);
DROP TABLE IF EXISTS "knex_migrations_lock";
CREATE TABLE "knex_migrations_lock" ("is_locked" integer);
INSERT INTO "knex_migrations_lock" VALUES(0);
DROP TABLE IF EXISTS "movies";
CREATE TABLE "movies" ("id" integer not null primary key autoincrement, "title" varchar(255), "genre" varchar(255), "classification" varchar(255), "rating" integer);
INSERT INTO "movies" VALUES(1,'Finding Nemo','Family','G',82);
INSERT INTO "movies" VALUES(2,'Shawshank Redemption','Drama','R18',93);
INSERT INTO "movies" VALUES(3,'Gladiator','Action','M15',85);
INSERT INTO "movies" VALUES(4,'Cinderella','Family','G',70);
DROP TABLE IF EXISTS "users";
CREATE TABLE "users" ("id" integer not null primary key autoincrement, "name" varchar(255), "age" integer);
INSERT INTO "users" VALUES(1,'Brady',22);
INSERT INTO "users" VALUES(2,'Lisa',25);
INSERT INTO "users" VALUES(3,'Steve',12);
INSERT INTO "users" VALUES(4,'Ben',27);
